#' \code{squashinformr} package
#'
#' Google spreadsheets R API
#'
#' See the README on \href{https://github.com/HaydenMacDonald/squashinformr}{GitHub}
#'
#' @docType package
#' @name squashinformr
NULL

## quiets concerns of R CMD check re: the .'s that appear in pipelines
if(getRversion() >= "3.4.0")  utils::globalVariables(c(".",
                                                       "g",
                                                       "hwr",
                                                       "name",
                                                       "gender",
                                                       "ranking_month",
                                                       "ranking_year",
                                                       "exact_date",
                                                       "Rank",
                                                       "Name",
                                                       "Year",
                                                       "rnd",
                                                       "ctry",
                                                       "w_l",
                                                       "opponent",
                                                       "score",
                                                       "match_time",
                                                       "points_won",
                                                       "points_lost",
                                                       "game_result",
                                                       "event",
                                                       "country",
                                                       "psa",
                                                       "result",
                                                       "games_won",
                                                       "games_lost",
                                                       "seeding",
                                                       "tour",
                                                       "round_reached",
                                                       "event_date",
                                                       "rowid",
                                                       "value",
                                                       "age",
                                                       "birthplace",
                                                       "residence",
                                                       "height",
                                                       "weight",
                                                       "plays",
                                                       "racket",
                                                       "joined_psa",
                                                       "coach",
                                                       "university",
                                                       "club",
                                                       "prev",
                                                       "previous_rank",
                                                       "highest_world_ranking",
                                                       "hwr_date",
                                                       "highest_ranking",
                                                       "x",
                                                       "league",
                                                       "setNames",
                                                       "X1",
                                                       "X2",
                                                       "player_1",
                                                       "player_2",
                                                       "tournament_name",
                                                       "tournament_date",
                                                       "match_winner",
                                                       "player_1_seed",
                                                       "player_2_seed",
                                                       "player_1_nationality",
                                                       "player_2_nationality",
                                                       "player_1_score",
                                                       "player_2_score",
                                                       "category",
                                                       "games",
                                                       "games_won",
                                                       "games_lost",
                                                       "player",
                                                       "player_seed",
                                                       "seed",
                                                       "city",
                                                       "game",
                                                       "game_winner",
                                                       "player_nationality",
                                                       "nationality"))
